# Generated by Django 5.2.17 on 2026-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Meetup', 'Meetup'), ('Workshop', 'Workshop'), ('Webinar', 'Webinar'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
