# Generated by Django 5.2.17 on 2026-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conference', 'conference'), ('Meetup', 'meetup'), ('Workshop', 'workshop'), ('Webinar', 'webinar'), ('Other', 'other')], default='Other', max_length=255),
        ),
    ]
