# Generated by Django 5.2.17 on 2026-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'conference'), ('meetup', 'meetup'), ('workshop', 'workshop'), ('webinar', 'webinar'), ('other', 'other')], default='other', max_length=255),
        ),
    ]
